def longest_palindrome(word)
  palindromes = []
  (1..word.size).each do |word_length|
    word.split('').each_cons(word_length) do |letters|
      palindromes << letters.join if letters.join == letters.join.reverse
    end
  end

  palindromes.max_by(&:length)
end

longest_palindrome "afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd" # => "dhfdkjfffhhfffjkdfhd"
# >> dhfdkjfffhhfffjkdfhd
# >> a
# >> f
# >> b
# >> b
# >> b
# >> f
# >> j
# >> d
# >> j
# >> k
# >> l
# >> g
# >> d
# >> f
# >> d
# >> h
# >> f
# >> d
# >> k
# >> j
# >> f
# >> f
# >> f
# >> h
# >> h
# >> f
# >> f
# >> f
# >> j
# >> k
# >> d
# >> f
# >> h
# >> d
# >> h
# >> k
# >> y
# >> e
# >> j
# >> e
# >> j
# >> f
# >> j
# >> k
# >> d
# >> af
# >> fb
# >> bb
# >> bb
# >> bf
# >> fj
# >> jd
# >> dj
# >> jk
# >> kl
# >> lg
# >> gd
# >> df
# >> fd
# >> dh
# >> hf
# >> fd
# >> dk
# >> kj
# >> jf
# >> ff
# >> ff
# >> fh
# >> hh
# >> hf
# >> ff
# >> ff
# >> fj
# >> jk
# >> kd
# >> df
# >> fh
# >> hd
# >> dh
# >> hk
# >> ky
# >> ye
# >> ej
# >> je
# >> ej
# >> jf
# >> fj
# >> jk
# >> kd
# >> afb
# >> fbb
# >> bbb
# >> bbf
# >> bfj
# >> fjd
# >> jdj
# >> djk
# >> jkl
# >> klg
# >> lgd
# >> gdf
# >> dfd
# >> fdh
# >> dhf
# >> hfd
# >> fdk
# >> dkj
# >> kjf
# >> jff
# >> fff
# >> ffh
# >> fhh
# >> hhf
# >> hff
# >> fff
# >> ffj
# >> fjk
# >> jkd
# >> kdf
# >> dfh
# >> fhd
# >> hdh
# >> dhk
# >> hky
# >> kye
# >> yej
# >> eje
# >> jej
# >> ejf
# >> jfj
# >> fjk
# >> jkd
# >> afbb
# >> fbbb
# >> bbbf
# >> bbfj
# >> bfjd
# >> fjdj
# >> jdjk
# >> djkl
# >> jklg
# >> klgd
# >> lgdf
# >> gdfd
# >> dfdh
# >> fdhf
# >> dhfd
# >> hfdk
# >> fdkj
# >> dkjf
# >> kjff
# >> jfff
# >> fffh
# >> ffhh
# >> fhhf
# >> hhff
# >> hfff
# >> fffj
# >> ffjk
# >> fjkd
# >> jkdf
# >> kdfh
# >> dfhd
# >> fhdh
# >> hdhk
# >> dhky
# >> hkye
# >> kyej
# >> yeje
# >> ejej
# >> jejf
# >> ejfj
# >> jfjk
# >> fjkd
# >> afbbb
# >> fbbbf
# >> bbbfj
# >> bbfjd
# >> bfjdj
# >> fjdjk
# >> jdjkl
# >> djklg
# >> jklgd
# >> klgdf
# >> lgdfd
# >> gdfdh
# >> dfdhf
# >> fdhfd
# >> dhfdk
# >> hfdkj
# >> fdkjf
# >> dkjff
# >> kjfff
# >> jfffh
# >> fffhh
# >> ffhhf
# >> fhhff
# >> hhfff
# >> hfffj
# >> fffjk
# >> ffjkd
# >> fjkdf
# >> jkdfh
# >> kdfhd
# >> dfhdh
# >> fhdhk
# >> hdhky
# >> dhkye
# >> hkyej
# >> kyeje
# >> yejej
# >> ejejf
# >> jejfj
# >> ejfjk
# >> jfjkd
# >> afbbbf
# >> fbbbfj
# >> bbbfjd
# >> bbfjdj
# >> bfjdjk
# >> fjdjkl
# >> jdjklg
# >> djklgd
# >> jklgdf
# >> klgdfd
# >> lgdfdh
# >> gdfdhf
# >> dfdhfd
# >> fdhfdk
# >> dhfdkj
# >> hfdkjf
# >> fdkjff
# >> dkjfff
# >> kjfffh
# >> jfffhh
# >> fffhhf
# >> ffhhff
# >> fhhfff
# >> hhfffj
# >> hfffjk
# >> fffjkd
# >> ffjkdf
# >> fjkdfh
# >> jkdfhd
# >> kdfhdh
# >> dfhdhk
# >> fhdhky
# >> hdhkye
# >> dhkyej
# >> hkyeje
# >> kyejej
# >> yejejf
# >> ejejfj
# >> jejfjk
# >> ejfjkd
# >> afbbbfj
# >> fbbbfjd
# >> bbbfjdj
# >> bbfjdjk
# >> bfjdjkl
# >> fjdjklg
# >> jdjklgd
# >> djklgdf
# >> jklgdfd
# >> klgdfdh
# >> lgdfdhf
# >> gdfdhfd
# >> dfdhfdk
# >> fdhfdkj
# >> dhfdkjf
# >> hfdkjff
# >> fdkjfff
# >> dkjfffh
# >> kjfffhh
# >> jfffhhf
# >> fffhhff
# >> ffhhfff
# >> fhhfffj
# >> hhfffjk
# >> hfffjkd
# >> fffjkdf
# >> ffjkdfh
# >> fjkdfhd
# >> jkdfhdh
# >> kdfhdhk
# >> dfhdhky
# >> fhdhkye
# >> hdhkyej
# >> dhkyeje
# >> hkyejej
# >> kyejejf
# >> yejejfj
# >> ejejfjk
# >> jejfjkd
# >> afbbbfjd
# >> fbbbfjdj
# >> bbbfjdjk
# >> bbfjdjkl
# >> bfjdjklg
# >> fjdjklgd
# >> jdjklgdf
# >> djklgdfd
# >> jklgdfdh
# >> klgdfdhf
# >> lgdfdhfd
# >> gdfdhfdk
# >> dfdhfdkj
# >> fdhfdkjf
# >> dhfdkjff
# >> hfdkjfff
# >> fdkjfffh
# >> dkjfffhh
# >> kjfffhhf
# >> jfffhhff
# >> fffhhfff
# >> ffhhfffj
# >> fhhfffjk
# >> hhfffjkd
# >> hfffjkdf
# >> fffjkdfh
# >> ffjkdfhd
# >> fjkdfhdh
# >> jkdfhdhk
# >> kdfhdhky
# >> dfhdhkye
# >> fhdhkyej
# >> hdhkyeje
# >> dhkyejej
# >> hkyejejf
# >> kyejejfj
# >> yejejfjk
# >> ejejfjkd
# >> afbbbfjdj
# >> fbbbfjdjk
# >> bbbfjdjkl
# >> bbfjdjklg
# >> bfjdjklgd
# >> fjdjklgdf
# >> jdjklgdfd
# >> djklgdfdh
# >> jklgdfdhf
# >> klgdfdhfd
# >> lgdfdhfdk
# >> gdfdhfdkj
# >> dfdhfdkjf
# >> fdhfdkjff
# >> dhfdkjfff
# >> hfdkjfffh
# >> fdkjfffhh
# >> dkjfffhhf
# >> kjfffhhff
# >> jfffhhfff
# >> fffhhfffj
# >> ffhhfffjk
# >> fhhfffjkd
# >> hhfffjkdf
# >> hfffjkdfh
# >> fffjkdfhd
# >> ffjkdfhdh
# >> fjkdfhdhk
# >> jkdfhdhky
# >> kdfhdhkye
# >> dfhdhkyej
# >> fhdhkyeje
# >> hdhkyejej
# >> dhkyejejf
# >> hkyejejfj
# >> kyejejfjk
# >> yejejfjkd
# >> afbbbfjdjk
# >> fbbbfjdjkl
# >> bbbfjdjklg
# >> bbfjdjklgd
# >> bfjdjklgdf
# >> fjdjklgdfd
# >> jdjklgdfdh
# >> djklgdfdhf
# >> jklgdfdhfd
# >> klgdfdhfdk
# >> lgdfdhfdkj
# >> gdfdhfdkjf
# >> dfdhfdkjff
# >> fdhfdkjfff
# >> dhfdkjfffh
# >> hfdkjfffhh
# >> fdkjfffhhf
# >> dkjfffhhff
# >> kjfffhhfff
# >> jfffhhfffj
# >> fffhhfffjk
# >> ffhhfffjkd
# >> fhhfffjkdf
# >> hhfffjkdfh
# >> hfffjkdfhd
# >> fffjkdfhdh
# >> ffjkdfhdhk
# >> fjkdfhdhky
# >> jkdfhdhkye
# >> kdfhdhkyej
# >> dfhdhkyeje
# >> fhdhkyejej
# >> hdhkyejejf
# >> dhkyejejfj
# >> hkyejejfjk
# >> kyejejfjkd
# >> afbbbfjdjkl
# >> fbbbfjdjklg
# >> bbbfjdjklgd
# >> bbfjdjklgdf
# >> bfjdjklgdfd
# >> fjdjklgdfdh
# >> jdjklgdfdhf
# >> djklgdfdhfd
# >> jklgdfdhfdk
# >> klgdfdhfdkj
# >> lgdfdhfdkjf
# >> gdfdhfdkjff
# >> dfdhfdkjfff
# >> fdhfdkjfffh
# >> dhfdkjfffhh
# >> hfdkjfffhhf
# >> fdkjfffhhff
# >> dkjfffhhfff
# >> kjfffhhfffj
# >> jfffhhfffjk
# >> fffhhfffjkd
# >> ffhhfffjkdf
# >> fhhfffjkdfh
# >> hhfffjkdfhd
# >> hfffjkdfhdh
# >> fffjkdfhdhk
# >> ffjkdfhdhky
# >> fjkdfhdhkye
# >> jkdfhdhkyej
# >> kdfhdhkyeje
# >> dfhdhkyejej
# >> fhdhkyejejf
# >> hdhkyejejfj
# >> dhkyejejfjk
# >> hkyejejfjkd
# >> afbbbfjdjklg
# >> fbbbfjdjklgd
# >> bbbfjdjklgdf
# >> bbfjdjklgdfd
# >> bfjdjklgdfdh
# >> fjdjklgdfdhf
# >> jdjklgdfdhfd
# >> djklgdfdhfdk
# >> jklgdfdhfdkj
# >> klgdfdhfdkjf
# >> lgdfdhfdkjff
# >> gdfdhfdkjfff
# >> dfdhfdkjfffh
# >> fdhfdkjfffhh
# >> dhfdkjfffhhf
# >> hfdkjfffhhff
# >> fdkjfffhhfff
# >> dkjfffhhfffj
# >> kjfffhhfffjk
# >> jfffhhfffjkd
# >> fffhhfffjkdf
# >> ffhhfffjkdfh
# >> fhhfffjkdfhd
# >> hhfffjkdfhdh
# >> hfffjkdfhdhk
# >> fffjkdfhdhky
# >> ffjkdfhdhkye
# >> fjkdfhdhkyej
# >> jkdfhdhkyeje
# >> kdfhdhkyejej
# >> dfhdhkyejejf
# >> fhdhkyejejfj
# >> hdhkyejejfjk
# >> dhkyejejfjkd
# >> afbbbfjdjklgd
# >> fbbbfjdjklgdf
# >> bbbfjdjklgdfd
# >> bbfjdjklgdfdh
# >> bfjdjklgdfdhf
# >> fjdjklgdfdhfd
# >> jdjklgdfdhfdk
# >> djklgdfdhfdkj
# >> jklgdfdhfdkjf
# >> klgdfdhfdkjff
# >> lgdfdhfdkjfff
# >> gdfdhfdkjfffh
# >> dfdhfdkjfffhh
# >> fdhfdkjfffhhf
# >> dhfdkjfffhhff
# >> hfdkjfffhhfff
# >> fdkjfffhhfffj
# >> dkjfffhhfffjk
# >> kjfffhhfffjkd
# >> jfffhhfffjkdf
# >> fffhhfffjkdfh
# >> ffhhfffjkdfhd
# >> fhhfffjkdfhdh
# >> hhfffjkdfhdhk
# >> hfffjkdfhdhky
# >> fffjkdfhdhkye
# >> ffjkdfhdhkyej
# >> fjkdfhdhkyeje
# >> jkdfhdhkyejej
# >> kdfhdhkyejejf
# >> dfhdhkyejejfj
# >> fhdhkyejejfjk
# >> hdhkyejejfjkd
# >> afbbbfjdjklgdf
# >> fbbbfjdjklgdfd
# >> bbbfjdjklgdfdh
# >> bbfjdjklgdfdhf
# >> bfjdjklgdfdhfd
# >> fjdjklgdfdhfdk
# >> jdjklgdfdhfdkj
# >> djklgdfdhfdkjf
# >> jklgdfdhfdkjff
# >> klgdfdhfdkjfff
# >> lgdfdhfdkjfffh
# >> gdfdhfdkjfffhh
# >> dfdhfdkjfffhhf
# >> fdhfdkjfffhhff
# >> dhfdkjfffhhfff
# >> hfdkjfffhhfffj
# >> fdkjfffhhfffjk
# >> dkjfffhhfffjkd
# >> kjfffhhfffjkdf
# >> jfffhhfffjkdfh
# >> fffhhfffjkdfhd
# >> ffhhfffjkdfhdh
# >> fhhfffjkdfhdhk
# >> hhfffjkdfhdhky
# >> hfffjkdfhdhkye
# >> fffjkdfhdhkyej
# >> ffjkdfhdhkyeje
# >> fjkdfhdhkyejej
# >> jkdfhdhkyejejf
# >> kdfhdhkyejejfj
# >> dfhdhkyejejfjk
# >> fhdhkyejejfjkd
# >> afbbbfjdjklgdfd
# >> fbbbfjdjklgdfdh
# >> bbbfjdjklgdfdhf
# >> bbfjdjklgdfdhfd
# >> bfjdjklgdfdhfdk
# >> fjdjklgdfdhfdkj
# >> jdjklgdfdhfdkjf
# >> djklgdfdhfdkjff
# >> jklgdfdhfdkjfff
# >> klgdfdhfdkjfffh
# >> lgdfdhfdkjfffhh
# >> gdfdhfdkjfffhhf
# >> dfdhfdkjfffhhff
# >> fdhfdkjfffhhfff
# >> dhfdkjfffhhfffj
# >> hfdkjfffhhfffjk
# >> fdkjfffhhfffjkd
# >> dkjfffhhfffjkdf
# >> kjfffhhfffjkdfh
# >> jfffhhfffjkdfhd
# >> fffhhfffjkdfhdh
# >> ffhhfffjkdfhdhk
# >> fhhfffjkdfhdhky
# >> hhfffjkdfhdhkye
# >> hfffjkdfhdhkyej
# >> fffjkdfhdhkyeje
# >> ffjkdfhdhkyejej
# >> fjkdfhdhkyejejf
# >> jkdfhdhkyejejfj
# >> kdfhdhkyejejfjk
# >> dfhdhkyejejfjkd
# >> afbbbfjdjklgdfdh
# >> fbbbfjdjklgdfdhf
# >> bbbfjdjklgdfdhfd
# >> bbfjdjklgdfdhfdk
# >> bfjdjklgdfdhfdkj
# >> fjdjklgdfdhfdkjf
# >> jdjklgdfdhfdkjff
# >> djklgdfdhfdkjfff
# >> jklgdfdhfdkjfffh
# >> klgdfdhfdkjfffhh
# >> lgdfdhfdkjfffhhf
# >> gdfdhfdkjfffhhff
# >> dfdhfdkjfffhhfff
# >> fdhfdkjfffhhfffj
# >> dhfdkjfffhhfffjk
# >> hfdkjfffhhfffjkd
# >> fdkjfffhhfffjkdf
# >> dkjfffhhfffjkdfh
# >> kjfffhhfffjkdfhd
# >> jfffhhfffjkdfhdh
# >> fffhhfffjkdfhdhk
# >> ffhhfffjkdfhdhky
# >> fhhfffjkdfhdhkye
# >> hhfffjkdfhdhkyej
# >> hfffjkdfhdhkyeje
# >> fffjkdfhdhkyejej
# >> ffjkdfhdhkyejejf
# >> fjkdfhdhkyejejfj
# >> jkdfhdhkyejejfjk
# >> kdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhf
# >> fbbbfjdjklgdfdhfd
# >> bbbfjdjklgdfdhfdk
# >> bbfjdjklgdfdhfdkj
# >> bfjdjklgdfdhfdkjf
# >> fjdjklgdfdhfdkjff
# >> jdjklgdfdhfdkjfff
# >> djklgdfdhfdkjfffh
# >> jklgdfdhfdkjfffhh
# >> klgdfdhfdkjfffhhf
# >> lgdfdhfdkjfffhhff
# >> gdfdhfdkjfffhhfff
# >> dfdhfdkjfffhhfffj
# >> fdhfdkjfffhhfffjk
# >> dhfdkjfffhhfffjkd
# >> hfdkjfffhhfffjkdf
# >> fdkjfffhhfffjkdfh
# >> dkjfffhhfffjkdfhd
# >> kjfffhhfffjkdfhdh
# >> jfffhhfffjkdfhdhk
# >> fffhhfffjkdfhdhky
# >> ffhhfffjkdfhdhkye
# >> fhhfffjkdfhdhkyej
# >> hhfffjkdfhdhkyeje
# >> hfffjkdfhdhkyejej
# >> fffjkdfhdhkyejejf
# >> ffjkdfhdhkyejejfj
# >> fjkdfhdhkyejejfjk
# >> jkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfd
# >> fbbbfjdjklgdfdhfdk
# >> bbbfjdjklgdfdhfdkj
# >> bbfjdjklgdfdhfdkjf
# >> bfjdjklgdfdhfdkjff
# >> fjdjklgdfdhfdkjfff
# >> jdjklgdfdhfdkjfffh
# >> djklgdfdhfdkjfffhh
# >> jklgdfdhfdkjfffhhf
# >> klgdfdhfdkjfffhhff
# >> lgdfdhfdkjfffhhfff
# >> gdfdhfdkjfffhhfffj
# >> dfdhfdkjfffhhfffjk
# >> fdhfdkjfffhhfffjkd
# >> dhfdkjfffhhfffjkdf
# >> hfdkjfffhhfffjkdfh
# >> fdkjfffhhfffjkdfhd
# >> dkjfffhhfffjkdfhdh
# >> kjfffhhfffjkdfhdhk
# >> jfffhhfffjkdfhdhky
# >> fffhhfffjkdfhdhkye
# >> ffhhfffjkdfhdhkyej
# >> fhhfffjkdfhdhkyeje
# >> hhfffjkdfhdhkyejej
# >> hfffjkdfhdhkyejejf
# >> fffjkdfhdhkyejejfj
# >> ffjkdfhdhkyejejfjk
# >> fjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdk
# >> fbbbfjdjklgdfdhfdkj
# >> bbbfjdjklgdfdhfdkjf
# >> bbfjdjklgdfdhfdkjff
# >> bfjdjklgdfdhfdkjfff
# >> fjdjklgdfdhfdkjfffh
# >> jdjklgdfdhfdkjfffhh
# >> djklgdfdhfdkjfffhhf
# >> jklgdfdhfdkjfffhhff
# >> klgdfdhfdkjfffhhfff
# >> lgdfdhfdkjfffhhfffj
# >> gdfdhfdkjfffhhfffjk
# >> dfdhfdkjfffhhfffjkd
# >> fdhfdkjfffhhfffjkdf
# >> dhfdkjfffhhfffjkdfh
# >> hfdkjfffhhfffjkdfhd
# >> fdkjfffhhfffjkdfhdh
# >> dkjfffhhfffjkdfhdhk
# >> kjfffhhfffjkdfhdhky
# >> jfffhhfffjkdfhdhkye
# >> fffhhfffjkdfhdhkyej
# >> ffhhfffjkdfhdhkyeje
# >> fhhfffjkdfhdhkyejej
# >> hhfffjkdfhdhkyejejf
# >> hfffjkdfhdhkyejejfj
# >> fffjkdfhdhkyejejfjk
# >> ffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkj
# >> fbbbfjdjklgdfdhfdkjf
# >> bbbfjdjklgdfdhfdkjff
# >> bbfjdjklgdfdhfdkjfff
# >> bfjdjklgdfdhfdkjfffh
# >> fjdjklgdfdhfdkjfffhh
# >> jdjklgdfdhfdkjfffhhf
# >> djklgdfdhfdkjfffhhff
# >> jklgdfdhfdkjfffhhfff
# >> klgdfdhfdkjfffhhfffj
# >> lgdfdhfdkjfffhhfffjk
# >> gdfdhfdkjfffhhfffjkd
# >> dfdhfdkjfffhhfffjkdf
# >> fdhfdkjfffhhfffjkdfh
# >> dhfdkjfffhhfffjkdfhd
# >> hfdkjfffhhfffjkdfhdh
# >> fdkjfffhhfffjkdfhdhk
# >> dkjfffhhfffjkdfhdhky
# >> kjfffhhfffjkdfhdhkye
# >> jfffhhfffjkdfhdhkyej
# >> fffhhfffjkdfhdhkyeje
# >> ffhhfffjkdfhdhkyejej
# >> fhhfffjkdfhdhkyejejf
# >> hhfffjkdfhdhkyejejfj
# >> hfffjkdfhdhkyejejfjk
# >> fffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjf
# >> fbbbfjdjklgdfdhfdkjff
# >> bbbfjdjklgdfdhfdkjfff
# >> bbfjdjklgdfdhfdkjfffh
# >> bfjdjklgdfdhfdkjfffhh
# >> fjdjklgdfdhfdkjfffhhf
# >> jdjklgdfdhfdkjfffhhff
# >> djklgdfdhfdkjfffhhfff
# >> jklgdfdhfdkjfffhhfffj
# >> klgdfdhfdkjfffhhfffjk
# >> lgdfdhfdkjfffhhfffjkd
# >> gdfdhfdkjfffhhfffjkdf
# >> dfdhfdkjfffhhfffjkdfh
# >> fdhfdkjfffhhfffjkdfhd
# >> dhfdkjfffhhfffjkdfhdh
# >> hfdkjfffhhfffjkdfhdhk
# >> fdkjfffhhfffjkdfhdhky
# >> dkjfffhhfffjkdfhdhkye
# >> kjfffhhfffjkdfhdhkyej
# >> jfffhhfffjkdfhdhkyeje
# >> fffhhfffjkdfhdhkyejej
# >> ffhhfffjkdfhdhkyejejf
# >> fhhfffjkdfhdhkyejejfj
# >> hhfffjkdfhdhkyejejfjk
# >> hfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjff
# >> fbbbfjdjklgdfdhfdkjfff
# >> bbbfjdjklgdfdhfdkjfffh
# >> bbfjdjklgdfdhfdkjfffhh
# >> bfjdjklgdfdhfdkjfffhhf
# >> fjdjklgdfdhfdkjfffhhff
# >> jdjklgdfdhfdkjfffhhfff
# >> djklgdfdhfdkjfffhhfffj
# >> jklgdfdhfdkjfffhhfffjk
# >> klgdfdhfdkjfffhhfffjkd
# >> lgdfdhfdkjfffhhfffjkdf
# >> gdfdhfdkjfffhhfffjkdfh
# >> dfdhfdkjfffhhfffjkdfhd
# >> fdhfdkjfffhhfffjkdfhdh
# >> dhfdkjfffhhfffjkdfhdhk
# >> hfdkjfffhhfffjkdfhdhky
# >> fdkjfffhhfffjkdfhdhkye
# >> dkjfffhhfffjkdfhdhkyej
# >> kjfffhhfffjkdfhdhkyeje
# >> jfffhhfffjkdfhdhkyejej
# >> fffhhfffjkdfhdhkyejejf
# >> ffhhfffjkdfhdhkyejejfj
# >> fhhfffjkdfhdhkyejejfjk
# >> hhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfff
# >> fbbbfjdjklgdfdhfdkjfffh
# >> bbbfjdjklgdfdhfdkjfffhh
# >> bbfjdjklgdfdhfdkjfffhhf
# >> bfjdjklgdfdhfdkjfffhhff
# >> fjdjklgdfdhfdkjfffhhfff
# >> jdjklgdfdhfdkjfffhhfffj
# >> djklgdfdhfdkjfffhhfffjk
# >> jklgdfdhfdkjfffhhfffjkd
# >> klgdfdhfdkjfffhhfffjkdf
# >> lgdfdhfdkjfffhhfffjkdfh
# >> gdfdhfdkjfffhhfffjkdfhd
# >> dfdhfdkjfffhhfffjkdfhdh
# >> fdhfdkjfffhhfffjkdfhdhk
# >> dhfdkjfffhhfffjkdfhdhky
# >> hfdkjfffhhfffjkdfhdhkye
# >> fdkjfffhhfffjkdfhdhkyej
# >> dkjfffhhfffjkdfhdhkyeje
# >> kjfffhhfffjkdfhdhkyejej
# >> jfffhhfffjkdfhdhkyejejf
# >> fffhhfffjkdfhdhkyejejfj
# >> ffhhfffjkdfhdhkyejejfjk
# >> fhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffh
# >> fbbbfjdjklgdfdhfdkjfffhh
# >> bbbfjdjklgdfdhfdkjfffhhf
# >> bbfjdjklgdfdhfdkjfffhhff
# >> bfjdjklgdfdhfdkjfffhhfff
# >> fjdjklgdfdhfdkjfffhhfffj
# >> jdjklgdfdhfdkjfffhhfffjk
# >> djklgdfdhfdkjfffhhfffjkd
# >> jklgdfdhfdkjfffhhfffjkdf
# >> klgdfdhfdkjfffhhfffjkdfh
# >> lgdfdhfdkjfffhhfffjkdfhd
# >> gdfdhfdkjfffhhfffjkdfhdh
# >> dfdhfdkjfffhhfffjkdfhdhk
# >> fdhfdkjfffhhfffjkdfhdhky
# >> dhfdkjfffhhfffjkdfhdhkye
# >> hfdkjfffhhfffjkdfhdhkyej
# >> fdkjfffhhfffjkdfhdhkyeje
# >> dkjfffhhfffjkdfhdhkyejej
# >> kjfffhhfffjkdfhdhkyejejf
# >> jfffhhfffjkdfhdhkyejejfj
# >> fffhhfffjkdfhdhkyejejfjk
# >> ffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhh
# >> fbbbfjdjklgdfdhfdkjfffhhf
# >> bbbfjdjklgdfdhfdkjfffhhff
# >> bbfjdjklgdfdhfdkjfffhhfff
# >> bfjdjklgdfdhfdkjfffhhfffj
# >> fjdjklgdfdhfdkjfffhhfffjk
# >> jdjklgdfdhfdkjfffhhfffjkd
# >> djklgdfdhfdkjfffhhfffjkdf
# >> jklgdfdhfdkjfffhhfffjkdfh
# >> klgdfdhfdkjfffhhfffjkdfhd
# >> lgdfdhfdkjfffhhfffjkdfhdh
# >> gdfdhfdkjfffhhfffjkdfhdhk
# >> dfdhfdkjfffhhfffjkdfhdhky
# >> fdhfdkjfffhhfffjkdfhdhkye
# >> dhfdkjfffhhfffjkdfhdhkyej
# >> hfdkjfffhhfffjkdfhdhkyeje
# >> fdkjfffhhfffjkdfhdhkyejej
# >> dkjfffhhfffjkdfhdhkyejejf
# >> kjfffhhfffjkdfhdhkyejejfj
# >> jfffhhfffjkdfhdhkyejejfjk
# >> fffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhf
# >> fbbbfjdjklgdfdhfdkjfffhhff
# >> bbbfjdjklgdfdhfdkjfffhhfff
# >> bbfjdjklgdfdhfdkjfffhhfffj
# >> bfjdjklgdfdhfdkjfffhhfffjk
# >> fjdjklgdfdhfdkjfffhhfffjkd
# >> jdjklgdfdhfdkjfffhhfffjkdf
# >> djklgdfdhfdkjfffhhfffjkdfh
# >> jklgdfdhfdkjfffhhfffjkdfhd
# >> klgdfdhfdkjfffhhfffjkdfhdh
# >> lgdfdhfdkjfffhhfffjkdfhdhk
# >> gdfdhfdkjfffhhfffjkdfhdhky
# >> dfdhfdkjfffhhfffjkdfhdhkye
# >> fdhfdkjfffhhfffjkdfhdhkyej
# >> dhfdkjfffhhfffjkdfhdhkyeje
# >> hfdkjfffhhfffjkdfhdhkyejej
# >> fdkjfffhhfffjkdfhdhkyejejf
# >> dkjfffhhfffjkdfhdhkyejejfj
# >> kjfffhhfffjkdfhdhkyejejfjk
# >> jfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhff
# >> fbbbfjdjklgdfdhfdkjfffhhfff
# >> bbbfjdjklgdfdhfdkjfffhhfffj
# >> bbfjdjklgdfdhfdkjfffhhfffjk
# >> bfjdjklgdfdhfdkjfffhhfffjkd
# >> fjdjklgdfdhfdkjfffhhfffjkdf
# >> jdjklgdfdhfdkjfffhhfffjkdfh
# >> djklgdfdhfdkjfffhhfffjkdfhd
# >> jklgdfdhfdkjfffhhfffjkdfhdh
# >> klgdfdhfdkjfffhhfffjkdfhdhk
# >> lgdfdhfdkjfffhhfffjkdfhdhky
# >> gdfdhfdkjfffhhfffjkdfhdhkye
# >> dfdhfdkjfffhhfffjkdfhdhkyej
# >> fdhfdkjfffhhfffjkdfhdhkyeje
# >> dhfdkjfffhhfffjkdfhdhkyejej
# >> hfdkjfffhhfffjkdfhdhkyejejf
# >> fdkjfffhhfffjkdfhdhkyejejfj
# >> dkjfffhhfffjkdfhdhkyejejfjk
# >> kjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfff
# >> fbbbfjdjklgdfdhfdkjfffhhfffj
# >> bbbfjdjklgdfdhfdkjfffhhfffjk
# >> bbfjdjklgdfdhfdkjfffhhfffjkd
# >> bfjdjklgdfdhfdkjfffhhfffjkdf
# >> fjdjklgdfdhfdkjfffhhfffjkdfh
# >> jdjklgdfdhfdkjfffhhfffjkdfhd
# >> djklgdfdhfdkjfffhhfffjkdfhdh
# >> jklgdfdhfdkjfffhhfffjkdfhdhk
# >> klgdfdhfdkjfffhhfffjkdfhdhky
# >> lgdfdhfdkjfffhhfffjkdfhdhkye
# >> gdfdhfdkjfffhhfffjkdfhdhkyej
# >> dfdhfdkjfffhhfffjkdfhdhkyeje
# >> fdhfdkjfffhhfffjkdfhdhkyejej
# >> dhfdkjfffhhfffjkdfhdhkyejejf
# >> hfdkjfffhhfffjkdfhdhkyejejfj
# >> fdkjfffhhfffjkdfhdhkyejejfjk
# >> dkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffj
# >> fbbbfjdjklgdfdhfdkjfffhhfffjk
# >> bbbfjdjklgdfdhfdkjfffhhfffjkd
# >> bbfjdjklgdfdhfdkjfffhhfffjkdf
# >> bfjdjklgdfdhfdkjfffhhfffjkdfh
# >> fjdjklgdfdhfdkjfffhhfffjkdfhd
# >> jdjklgdfdhfdkjfffhhfffjkdfhdh
# >> djklgdfdhfdkjfffhhfffjkdfhdhk
# >> jklgdfdhfdkjfffhhfffjkdfhdhky
# >> klgdfdhfdkjfffhhfffjkdfhdhkye
# >> lgdfdhfdkjfffhhfffjkdfhdhkyej
# >> gdfdhfdkjfffhhfffjkdfhdhkyeje
# >> dfdhfdkjfffhhfffjkdfhdhkyejej
# >> fdhfdkjfffhhfffjkdfhdhkyejejf
# >> dhfdkjfffhhfffjkdfhdhkyejejfj
# >> hfdkjfffhhfffjkdfhdhkyejejfjk
# >> fdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjk
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkd
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdf
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfh
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhd
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> djklgdfdhfdkjfffhhfffjkdfhdhky
# >> jklgdfdhfdkjfffhhfffjkdfhdhkye
# >> klgdfdhfdkjfffhhfffjkdfhdhkyej
# >> lgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> gdfdhfdkjfffhhfffjkdfhdhkyejej
# >> dfdhfdkjfffhhfffjkdfhdhkyejejf
# >> fdhfdkjfffhhfffjkdfhdhkyejejfj
# >> dhfdkjfffhhfffjkdfhdhkyejejfjk
# >> hfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkd
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdf
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfh
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhd
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> djklgdfdhfdkjfffhhfffjkdfhdhkye
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> klgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> lgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> gdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> dfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> fdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> dhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdf
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfh
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhd
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> klgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> lgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> gdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> dfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> fdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfh
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhd
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> klgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> lgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> gdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> dfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhd
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> klgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> lgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> gdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdh
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> klgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> lgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhk
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> klgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhky
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> jklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkye
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> djklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyej
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> jdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyeje
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> fjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejej
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> bfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejf
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> bbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfj
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> bbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjk
# >> fbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> afbbbfjdjklgdfdhfdkjfffhhfffjkdfhdhkyejejfjkd
# >> ["a", "f", "b", "b", "b", "f", "j", "d", "j", "k", "l", "g", "d", "f", "d", "h", "f", "d", "k", "j", "f", "f", "f", "h", "h", "f", "f", "f", "j", "k", "d", "f", "h", "d", "h", "k", "y", "e", "j", "e", "j", "f", "j", "k", "d", "bb", "bb", "ff", "ff", "hh", "ff", "ff", "bbb", "jdj", "dfd", "fff", "fff", "hdh", "eje", "jej", "jfj", "fhhf", "fbbbf", "ffhhff", "fffhhfff", "jfffhhfffj", "kjfffhhfffjk", "dkjfffhhfffjkd", "fdkjfffhhfffjkdf", "hfdkjfffhhfffjkdfh", "dhfdkjfffhhfffjkdfhd"]